test workflow

diff --git a/.github/workflows/test-workflow.yml b/.github/workflows/test-workflow.yml
--- a/.github/workflows/test-workflow.yml
+++ b/.github/workflows/test-workflow.yml
@@ -36,8 +36,12 @@ jobs:
       - name: Install required dependencies
         run: composer install
       - name: Create database
-        run: composer require --dev symfony/orm-pack
-          && php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+        run: |
+          composer require --dev symfony/orm-pack
+          php bin/console doctrine:database:drop --if-exists --force --env=test
+          php bin/console doctrine:database:create --if-not-exists --env=test
+          php bin/console doctrine:migrations:migrate --env=test || echo "No migrations found or migration failed"
+          php bin/console doctrine:fixtures:load --no-interaction
         env:
             DATABASE_URL: mysql://root:root@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/mydb_test
       - name: Run unit tests
